---

- hosts: all
  tasks:

  - name: update cache
    apt:
      update_cache: yes

  - name: Install Apache2
    # command: apt install apache2 -y   
    apt:
      name: apache2
      state: latest

  - name: Set timezone to Africa/Lagos
    timezone:
      name: Africa/Lagos

  - name: Display hostname
    shell: echo "<h1>Hello Altschool Africa!! This is $(hostname -f) and the date is $(date)</h1>" > /var/www/html/index.html
    notify: restart_apache

  handlers:
  - name: restart_apache
    service:
      name: apache2
      state: restarted